# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Maxim Lakin
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Coding projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "makslo.github.io" # the base hostname & protocol for your site
twitter_username: maksimum
github_username:  makslo

# Build settings
markdown: kramdown
